### ISSUE TITLE
Robot trajectory problem in ROS2 Foxy

### ISSUE THREAD

**Issue by Tianhuanyu** [mhubii/gravity_compensation#4]
Hi, @mhubii . I meet a problem with Gazebo simulation in Foxy.  When I run the second terminal for commanding trajectory, I find the robot executing a strange trajectory (Not only one-joint's motion). And the results are not saved in tmp file.

Is there something different between different ros version?

**Comment by mhubii** [comment]
hi @Tianhuanyu , there is currently a bug in the simulation. I'll try to fix it asap, dev-humble branch https://github.com/KCL-BMEIS/lbr_fri_ros2_stack/tree/dev-humble-minimal-refactor should work

**Comment by Tianhuanyu** [comment]
Thanks! @mhubii

**Comment by mhubii** [comment]
fixed
